# -*- mode: ruby -*-
# vi: set ft=ruby :

# Get the number of logical cpu cores.
def os_cpu_cores
  case RbConfig::CONFIG['host_os']
  when /darwin/
    Integer(`sysctl -n hw.ncpu`)
  when /linux/
    Integer(`cat /proc/cpuinfo | grep processor | wc -l`)
  else
    raise StandardError, "Unsupported platform"
  end
end

# Vagrant configuration.
Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "cross-compiler"
    vb.gui = false
    vb.memory = "16384"
    # Set CPU count to logical cores / 2.
    # See: https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/39
    vb.cpus = os_cpu_cores / 2
    vb.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    vb.customize ['modifyvm', :id, '--ioapic', 'on']
    vb.customize ['modifyvm', :id, '--audio', 'none']

    # See: https://www.jeffgeerling.com/blogs/jeff-geerling/mounting-raspberry-pis-ext4-sd
    # Requires "VirtualBox Extension Pack" to be installed.
    # vb.customize ["modifyvm", :id, "--usb", "on"]
    # vb.customize ["modifyvm", :id, "--usbxhci", "on"]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git bc sshfs bison flex libssl-dev make libc6-dev libncurses5-dev crossbuild-essential-armhf crossbuild-essential-arm64
  SHELL
end
